import type { ComponentType, SVGProps } from "react";
import {
  Activity,
  Ambulance,
  ArrowRight,
  Baby,
  Bandage,
  Bone,
  BookOpenText,
  Brain,
  Building2,
  CalendarDays,
  Camera,
  CheckCircle2,
  ClipboardCheck,
  ClipboardList,
  Clock3,
  Ear,
  Eye,
  FileText,
  Globe,
  HandHeart,
  Heart,
  HeartHandshake,
  HeartPulse,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  MessageSquare,
  Microscope,
  MoonStar,
  NotebookPen,
  Phone,
  Pill,
  ShieldCheck,
  Sparkles,
  Star,
  Stethoscope,
  Syringe,
  Target,
  TestTube2,
  UserRound,
  Users,
  Users2,
} from "lucide-react";

import type { CmsIconName } from "./types";

type IconComponent = ComponentType<SVGProps<SVGSVGElement>>;

export const cmsIcons: Record<CmsIconName, IconComponent> = {
  activity: Activity,
  ambulance: Ambulance,
  "arrow-right": ArrowRight,
  baby: Baby,
  bandage: Bandage,
  bone: Bone,
  "book-open": BookOpenText,
  brain: Brain,
  building: Building2,
  calendar: CalendarDays,
  camera: Camera,
  "check-circle": CheckCircle2,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  clock: Clock3,
  ear: Ear,
  eye: Eye,
  "file-text": FileText,
  globe: Globe,
  "hand-heart": HandHeart,
  heart: Heart,
  "heart-handshake": HeartHandshake,
  "heart-pulse": HeartPulse,
  lock: Lock,
  mail: Mail,
  "map-pin": MapPin,
  megaphone: Megaphone,
  "message-square": MessageSquare,
  microscope: Microscope,
  "moon-star": MoonStar,
  "notebook-pen": NotebookPen,
  phone: Phone,
  pill: Pill,
  shield: ShieldCheck,
  sparkles: Sparkles,
  star: Star,
  stethoscope: Stethoscope,
  syringe: Syringe,
  target: Target,
  "test-tube": TestTube2,
  "user-round": UserRound,
  users: Users,
  "users-2": Users2,
};

export const cmsIconOptions = Object.keys(cmsIcons) as CmsIconName[];

export function getCmsIcon(name?: CmsIconName) {
  return cmsIcons[name ?? "sparkles"] ?? Sparkles;
}
