import type { ComponentType, SVGProps } from "react";
import {
  Activity,
  Apple,
  Atom,
  Ambulance,
  ArrowRight,
  Baby,
  Bandage,
  BicepsFlexed,
  Bone,
  BookOpenText,
  Brain,
  BrainCircuit,
  BriefcaseMedical,
  Building2,
  CalendarDays,
  CalendarHeart,
  Camera,
  CheckCircle2,
  CirclePlus,
  ClipboardCheck,
  ClipboardList,
  ClipboardPlus,
  Clock3,
  Droplet,
  Ear,
  Eye,
  FilePlus2,
  FileText,
  Frown,
  Hand,
  Globe,
  HandHeart,
  Heart,
  HeartHandshake,
  HeartPulse,
  Hospital,
  Leaf,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  MessageSquare,
  Microscope,
  MonitorSmartphone,
  MoonStar,
  NotebookPen,
  PersonStanding,
  Phone,
  Pill,
  PillBottle,
  Ribbon,
  ScanText,
  ShieldCheck,
  Sparkles,
  Star,
  Stethoscope,
  SunMedium,
  Syringe,
  Tablets,
  Target,
  TestTube2,
  Thermometer,
  UserRound,
  UserRoundCheck,
  Users,
  Users2,
  WalletCards,
  Weight,
  Wind,
  Gauge,
} from "lucide-react";

import { GlucoseMeterIcon, LungsIcon, MaleSymbolIcon, UterusIcon } from "@/components/icons/medicalDesignIcons";
import type { CmsIconName } from "./types";

type IconComponent = ComponentType<SVGProps<SVGSVGElement>>;

export const cmsIcons: Record<CmsIconName, IconComponent> = {
  activity: Activity,
  apple: Apple,
  atom: Atom,
  ambulance: Ambulance,
  "arrow-right": ArrowRight,
  baby: Baby,
  bandage: Bandage,
  biceps: BicepsFlexed,
  bone: Bone,
  "book-open": BookOpenText,
  brain: Brain,
  "brain-circuit": BrainCircuit,
  "briefcase-medical": BriefcaseMedical,
  building: Building2,
  calendar: CalendarDays,
  "calendar-heart": CalendarHeart,
  camera: Camera,
  "check-circle": CheckCircle2,
  "circle-plus": CirclePlus,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  "clipboard-plus": ClipboardPlus,
  clock: Clock3,
  droplet: Droplet,
  ear: Ear,
  eye: Eye,
  "file-plus": FilePlus2,
  "file-text": FileText,
  frown: Frown,
  hand: Hand,
  globe: Globe,
  gauge: Gauge,
  "glucose-meter": GlucoseMeterIcon,
  "hand-heart": HandHeart,
  heart: Heart,
  "heart-handshake": HeartHandshake,
  "heart-pulse": HeartPulse,
  hospital: Hospital,
  leaf: Leaf,
  lock: Lock,
  lungs: LungsIcon,
  mail: Mail,
  "map-pin": MapPin,
  "male-symbol": MaleSymbolIcon,
  megaphone: Megaphone,
  "message-square": MessageSquare,
  microscope: Microscope,
  "monitor-smartphone": MonitorSmartphone,
  "moon-star": MoonStar,
  "notebook-pen": NotebookPen,
  "person-standing": PersonStanding,
  phone: Phone,
  pill: Pill,
  "pill-bottle": PillBottle,
  ribbon: Ribbon,
  "scan-text": ScanText,
  shield: ShieldCheck,
  sparkles: Sparkles,
  star: Star,
  stethoscope: Stethoscope,
  "sun-medium": SunMedium,
  syringe: Syringe,
  tablets: Tablets,
  target: Target,
  "test-tube": TestTube2,
  thermometer: Thermometer,
  "user-round": UserRound,
  "user-round-check": UserRoundCheck,
  uterus: UterusIcon,
  users: Users,
  "users-2": Users2,
  "wallet-cards": WalletCards,
  weight: Weight,
  wind: Wind,
};

export const cmsIconOptions = Object.keys(cmsIcons) as CmsIconName[];

export function getCmsIcon(name?: CmsIconName) {
  return cmsIcons[name ?? "sparkles"] ?? Sparkles;
}
